### ISSUE TITLE
mineysocket crashes after authentification

### ISSUE THREAD

**Issue by chrbinder** [miney-py/mineysocket#4]
After I authenticate my client, mineysockets crashes.
I am connecting remotely, using the latest mineysocket & Miney on Minetest 5.3.0. In this instance, I had to specifiy the port to connect even though it was the standard 29999.

`2021-02-18 09:44:27: ACTION[Server]: mineysocket: : New connection from 62.XXX.XXX.XXX 59359`
`2021-02-18 09:44:27: ACTION[Server]: mineysocket: : Received: {"playername": "XXXXXX", "password": "XXXXXX"}`
`2021-02-18 09:44:27: ACTION[Server]: mineysocket: Player 'XXXXX' authentication successful from XXX.XXX.XXX.XXX:59359`
`2021-02-18 09:44:27: ACTION[Main]: Server: Shutting down`
`2021-02-18 09:44:27: ACTION[Main]: mineysocket: Closing port...`
`2021-02-18 09:44:28: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod '' in callback environment_Step(): /home/XXX/minetest-live/bin/../mods/mineysocket/init.lua:328: attempt to concatenate local 'data' (a table value)`
`2021-02-18 09:44:28: ERROR[Main]: stack traceback:`
`2021-02-18 09:44:28: ERROR[Main]: 	/home/XXX/minetest-live/bin/../mods/mineysocket/init.lua:328: in function 'send'`
`2021-02-18 09:44:28: ERROR[Main]: 	/home/XXX/minetest-live/bin/../mods/mineysocket/init.lua:240: in function 'receive'`
`2021-02-18 09:44:28: ERROR[Main]: 	/home/XXX/minetest-live/bin/../mods/mineysocket/init.lua:81: in function </home/XXX/minetest-live/bin/../mods/mineysocket/init.lua:80>`
`2021-02-18 09:44:28: ERROR[Main]: 	/home/XXX/minetest-live/bin/../builtin/game/register.lua:429: in function </home/XXX/minetest-live/bin/../builtin/game/register.lua:413>`
`2021-02-18 09:44:28: ERROR[Main]: stack traceback:`

**Comment by Netzvamp** [comment]
Looks like you are using the master branch of mineysocket. Can you try this with the dev branch? I'll take a look to merge dev to master, if i've got time available.

**Comment by chrbinder** [comment]
Thanks a lot, using the dev branch seems to have solved the issue. I'm excited for futher development of the mod.
